name = 'juso-edge'
main = 'src/worker.ts'
compatibility_date = '2022-10-12'
compatibility_flags = [
  'url_standard',
]
workers_dev = true

[[kv_namespaces]]
binding = 'INDEX'
id = '0f9a0b3bcd504555b91373dca18fec94'
preview_id = '148ed37fafe24dce984d659acf035b89'

[vars]
USE_LOGFLARE = true
LOGFLARE_SOURCE = '1be10ca3-1885-4d6a-8892-d17cf9a2353b'

# [secrets]
# JUSO_CONFIRM_KEY
# LOGFLARE_API_KEY
